name: Resusable Workflow
on:
  workflow_call:
    inputs:
      name:
        description: 'Input description'
        type: string
        default: 'Mo'
        required: false
    secrets:
      access-toke:
        description: 'Secret descripotion'
        required: true
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls -a
  log-context-and-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Display Github Context
        run: echo '${{ toJson(Github) }}'
      - name: Display name input
        run: echo ${{inputs.name}}
      - name: Display access-token secret
        run: echo ${{ secrets.access.token }}